-- Generated by src/export_alert_rules.py from dim_alert_rule.csv.
-- Updates explanation text only. Thresholds and metrics are unchanged.
USE LegalAIObservatory;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
DECLARE @rules TABLE (rule_id INT PRIMARY KEY, rule_name NVARCHAR(200), rationale NVARCHAR(MAX));
INSERT @rules VALUES
(15, N'Lawyer mandatory review completion below 70%', N'Low mandatory review completion identifies cases for follow-up, not a finding of misconduct. The full-window Top 20 comparison is recorded in results/screening_comparison.csv and rendered in the rule catalogue. It uses synthetic ground truth withheld from the report, not an independent test sample. Lawyers with fewer than 25 mandatory outputs are excluded by the eligibility rule. A quarterly alert or a different filter requires its own evaluation. Incomplete review can also reflect delay rather than deliberate non-compliance.'),
(16, N'Restricted-tier session rate above 3x the firm median', N'Sensitive-session exposure provides context for the review list. Assignment to sensitive matters can drive this rate without implying misconduct. The full-window Top 20 comparison in results/screening_comparison.csv shows why exposure alone is a weaker screen in this synthetic scenario. The catalogue renders those results separately from this quarterly alert threshold.');
BEGIN TRY
    BEGIN TRANSACTION;
    IF (SELECT COUNT(*) FROM dbo.dim_alert_rule AS r JOIN @rules AS n
        ON r.rule_id = n.rule_id AND r.rule_name = n.rule_name) <> 2
        THROW 51000, 'Expected rule IDs and names were not found. No changes applied.', 1;
    UPDATE r SET rationale = n.rationale
    FROM dbo.dim_alert_rule AS r JOIN @rules AS n ON r.rule_id = n.rule_id
    WHERE r.rationale <> n.rationale OR r.rationale IS NULL;
    SELECT @@ROWCOUNT AS updated_rationales;
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
